<?php

 ?>

<nav>
    <a href="index.php">Acceuil</a>
    <a href="vuecontroleurs/AjoutBien.php" >ajouter Bien</a>
    <a>supprimer Bien</a>
    <a href="vuecontroleurs/affichageBiens.php">lister les Biens</a>
    <a>modifier Biens</a>
    <a href="vuecontroleurs/AffichageBiens.php">Affichage Biens</a>
    <a href="vuecontroleurs/RechercheBien.php">Recherche Bien</a>
    <a href="vuecontroleurs/changerMDP.php">Changer le mot de passe</a>
    <a href="vuecontroleurs/Deconnexion.php">Deconnexion</a>
</nav>

